title: bubbly.world
email: guy.paterson.jones@gmail.com
description: >- # ignore newlines
  math addict, climbs rocks
baseurl: "/blog"
url: "https://bubbly.world"
icon: /assets/images/icon-512.png
github_username: bubblyworld

# Build settings
markdown: kramdown
hide_credits: true

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"
